### ISSUE TITLE
[FEATURE]: Border Glow Effect

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#154]
### Feature Description 📝

This is a simple effect that adds a border glow that follows the mouse position.

https://github.com/Ansub/SyntaxUI/assets/16091805/a096200b-b604-40f9-ab2c-0dd86a21c6e0

### Motivation 🌟

Similar to the inputs in Aceternity UI's Signup Form https://ui.aceternity.com/components/signup-form

### Expected Behavior 🤔

https://github.com/Ansub/SyntaxUI/assets/16091805/a096200b-b604-40f9-ab2c-0dd86a21c6e0

**Comment by Ansub** [comment]
This can be a button, i don't see any need of this in effects section atm but in button it will look really sick.

I will be adding some card or testimonal components in future so can use this code there aswell

**Comment by epoll31** [comment]
The reason I kept it as an effect instead of a button is so that users can transform it into whatever they want easier. Because it could be a card, an input, a button, or whatever.

What do you think about me implementing it as a button so that there are tap and hover effects and implementing it as an effect so that others can take the barebones and run with it.

I got the idea from AceturnityUI's Signup Form because in that it is heavily integrated into the input, but I feel like users would really like to be able to take the effect and use it wherever they want.

**Comment by Ansub** [comment]
yeah but i dont want to give users raw code for inspiration, otherwise the opinionated angle of the UI will be gone, this will look better in button as it looks like a button. 

each thing we put out should directly be related to whether user can use it or not, if not then we should avoid it. i feel that this can easily be used in a button so it can find it's place in button. 

and if someone really wants to integrate this in card they can just copy the button code and convert it to card or whatever they want, possibilities are endless.

**Comment by epoll31** [comment]
Sounds good, i can get started on that
